### ISSUE TITLE
Naming clash for dockerVersion

### ISSUE THREAD

**Issue by itachi3** [zalando-incubator/sbt-stups#5]
Getting a name clash for 
`addSbtPlugin("org.zalando" % "sbt-stups" % "0.3.0")`
with 
`addSbtPlugin("com.typesafe.sbt" % "sbt-native-packager" % "1.3.2")`

`Some keys were defined with the same name but different types: 'dockerVersion' (java.lang.String, sbt.Task[scala.Option[com.typesafe.sbt.packager.docker.DockerVersion]])`

**Comment by mdedetrich** [comment]
@itachi3 Thanks for the PR

Note that this is a temporary solution. sbt-stups is designed to use the same key, the difference is that with some (new?) release of sbt-native-packager/sbt-docker the type of docker version has changed.

I will make the keys the same again with a new PR and make sure the types line up
